name: "Write to AstraDB"
topics:
  - name: "vectorized-midi-topic"
    creation-mode: create-if-not-exists
assets:
  - name: "vectorized-midi-table"
    asset-type: "cassandra-table"
    creation-mode: create-if-not-exists
    config:
      table-name: "documents"
      keyspace: "documents"
      datasource: "AstraDatasource"
      create-statements:
        - |
          CREATE TABLE IF NOT EXISTS documents.documents (
          filename TEXT,
          chunk_id int,
          num_tokens int,
          language TEXT,
          text TEXT,
          embeddings_vector VECTOR<FLOAT, 1536>,
          PRIMARY KEY (filename, chunk_id));
        - |
          CREATE CUSTOM INDEX IF NOT EXISTS documents_ann_index ON documents.documents(embeddings_vector) USING 'StorageAttachedIndex';
pipeline:
  - name: "Write to Astra"
    type: "vector-db-sink"
    input: "chunks-topic"
    resources:
      size: 2
    configuration:
      datasource: "AstraDatasource"
      table-name: "documents"
      keyspace: "documents"
      mapping: "filename=value.filename, chunk_id=value.chunk_id, language=value.language, text=value.text, embeddings_vector=value.embeddings_vector, num_tokens=value.chunk_num_tokens"